import React, { createContext, useContext } from "react";

export type Language = "zh" | "vi";
export type Theme = "light" | "dark";

export const TRANSLATIONS = {
  zh: {
    appName: "MPTV 项目管理系统",
    login: "登录",
    register: "注册",
    username: "用户名",
    password: "密码",
    email: "邮箱",
    dashboard: "仪表盘",
    projectFiles: "项目文件",
    archives: "归档",
    search: "搜索...",
    newProject: "新建项目",
    weeklyReport: "周报",
    logout: "退出登录",
    createTask: "创建任务",
    editTask: "编辑任务",
    taskTitle: "任务标题",
    description: "描述",
    priority: "优先级",
    assignee: "负责人",
    planStart: "计划开始",
    planEnd: "计划结束",
    actStart: "实际开始",
    actEnd: "实际结束",
    parentTask: "父任务",
    nextTask: "后续关联任务",
    attachments: "附件",
    active: "进行中",
    inactive: "已归档",
    status: "状态",
    save: "保存",
    cancel: "取消",
    delete: "删除",
    files: "文件",
    upload: "上传",
    download: "下载",
    downloadSelected: "下载已选",
    settings: "设置",
    editProfile: "编辑个人信息",
    updateProfile: "更新个人信息",
    newPassword: "新密码",
    noFiles: "暂无文件",
    allProjects: "全部项目",
    selectProjects: "选择项目",
    invertSelection: "反选",
    generate: "生成",
    startDate: "开始日期",
    endDate: "结束日期",
    previewMode: "演示账号：admin / 123456",
    overviewActiveProjects: "查看所有活跃项目概览。",
    inactiveProjects: "已停用项目列表。",
    browseFilesByProject: "按项目目录浏览文件。",
    noActiveProjectsFound: "未找到活跃项目。",
    noArchivedProjectsFound: "未找到归档项目。",
    prev: "上一页",
    next: "下一页",
    page: "第",
    projectCreated: "项目已创建。",
    projectCreationFailed: "创建项目失败",
    projectNamePlaceholder: "项目名称",
    creating: "创建中...",
    reportGenerated: "周报已生成。",
    reportGenerationFailed: "生成周报失败",
    generating: "生成中...",
    fileColumn: "文件",
    taskColumn: "任务",
    uploadedColumn: "上传时间",
    sizeColumn: "大小",
    actionsColumn: "操作",
    loading: "加载中...",
    retry: "重试",
    projectNotSelected: "未选择项目。",
    chooseAtLeastOneFile: "请至少选择一个文件。",
    downloadsStarted: "已开始下载 {count} 个文件。",
    downloadsFailed: "有 {count} 个文件获取下载链接失败。",
    failedLoadFiles: "加载文件失败",
    failedLoadProjectTasks: "加载项目任务失败",
    uploadedFiles: "已上传 {count} 个文件。",
    fileUploadFailed: "文件上传失败",
    failedDownloadFile: "下载文件失败",
    uploadFiles: "上传文件",
    targetTask: "目标任务",
    projectSharedFolder: "项目公共目录（不关联任务）",
    selectedFiles: "已选择 {count} 个文件",
    noFilesSelected: "未选择文件",
    uploading: "上传中...",
    failedLoadProject: "加载项目失败",
    taskUpdated: "任务已更新。",
    taskCreated: "任务已创建。",
    taskSaveFailed: "保存任务失败",
    deleteTaskConfirm: "确认删除该任务吗？",
    taskDeleted: "任务已删除。",
    taskDeletionFailed: "删除任务失败",
    taskUpdateFailed: "更新任务失败",
    projectUpdated: "项目已更新。",
    projectUpdateFailed: "更新项目失败",
    attachmentUploaded: "附件上传成功。",
    uploadFailed: "上传失败",
    attachmentDeleted: "附件已删除。",
    attachmentDeletionFailed: "删除附件失败",
    loadingProject: "项目加载中...",
    projectNotFound: "未找到项目。",
    back: "返回",
    board: "看板",
    gantt: "甘特图",
    table: "表格",
    projects: "项目",
    projectName: "项目名称",
    taskId: "任务 #",
    priorityHigh: "高",
    priorityMedium: "中",
    priorityLow: "低",
    none: "无",
    progressPercent: "进度 (%)",
    remarks: "备注",
    noAttachments: "暂无附件",
    saving: "保存中...",
    subTask: "子任务",
    plannedVsActualTimeline: "计划与实际时间线",
    zoomDay: "天",
    zoomWeek: "周",
    zoomMonth: "月",
    taskName: "任务名称",
    notes: "备注",
    unassigned: "未分配",
    columnTodo: "待办",
    columnInProgress: "进行中",
    columnDone: "已完成",
    columnWontDo: "不处理",
    columnBacklog: "待规划",
    accountCreated: "账号已创建，请登录。",
    authenticationFailed: "认证失败",
    enterpriseTagline: "企业级项目管理",
    processing: "处理中...",
    profileUpdated: "个人信息已更新。",
    profileUpdateFailed: "更新个人信息失败",
    failedInitializeApp: "应用初始化失败",
    failedLoadProjects: "加载项目失败",
    failedRefreshProjects: "刷新项目失败",
    downloadFailed: "下载失败",
    previewPlaceholderPdf: "PDF 预览占位（待接入在线预览）",
    previewNotAvailable: "当前文件类型暂不支持预览。"
  },
  vi: {
    appName: "MPTV Project Management",
    login: "Dang nhap",
    register: "Dang ky",
    username: "Ten dang nhap",
    password: "Mat khau",
    email: "Email",
    dashboard: "Bang dieu khien",
    projectFiles: "Tai lieu du an",
    archives: "Luu tru",
    search: "Tim kiem...",
    newProject: "Du an moi",
    weeklyReport: "Bao cao tuan",
    logout: "Dang xuat",
    createTask: "Tao nhiem vu",
    editTask: "Sua nhiem vu",
    taskTitle: "Tieu de",
    description: "Mo ta",
    priority: "Uu tien",
    assignee: "Nguoi phu trach",
    planStart: "Bat dau ke hoach",
    planEnd: "Ket thuc ke hoach",
    actStart: "Bat dau thuc te",
    actEnd: "Ket thuc thuc te",
    parentTask: "Nhiem vu cha",
    nextTask: "Nhiem vu lien quan",
    attachments: "Dinh kem",
    active: "Hoat dong",
    inactive: "Khong hoat dong",
    status: "Trang thai",
    save: "Luu",
    cancel: "Huy",
    delete: "Xoa",
    files: "Tep tin",
    upload: "Tai len",
    download: "Tai xuong",
    downloadSelected: "Tai duoc chon",
    settings: "Cai dat",
    editProfile: "Sua ho so",
    updateProfile: "Cap nhat ho so",
    newPassword: "Mat khau moi",
    noFiles: "Khong co tep tin",
    allProjects: "Tat ca du an",
    selectProjects: "Chon du an",
    invertSelection: "Dao nguoc",
    generate: "Tao bao cao",
    startDate: "Ngay bat dau",
    endDate: "Ngay ket thuc",
    previewMode: "Tai khoan demo: admin / 123456",
    overviewActiveProjects: "Tong quan tat ca du an dang hoat dong.",
    inactiveProjects: "Cac du an khong con hoat dong.",
    browseFilesByProject: "Duyet tep theo thu muc du an.",
    noActiveProjectsFound: "Khong tim thay du an dang hoat dong.",
    noArchivedProjectsFound: "Khong tim thay du an luu tru.",
    prev: "Truoc",
    next: "Sau",
    page: "Trang",
    projectCreated: "Da tao du an.",
    projectCreationFailed: "Tao du an that bai",
    projectNamePlaceholder: "Ten du an",
    creating: "Dang tao...",
    reportGenerated: "Da tao bao cao tuan.",
    reportGenerationFailed: "Tao bao cao that bai",
    generating: "Dang tao...",
    fileColumn: "Tep",
    taskColumn: "Nhiem vu",
    uploadedColumn: "Thoi gian tai len",
    sizeColumn: "Kich thuoc",
    actionsColumn: "Hanh dong",
    loading: "Dang tai...",
    retry: "Thu lai",
    projectNotSelected: "Chua chon du an.",
    chooseAtLeastOneFile: "Hay chon it nhat mot tep.",
    downloadsStarted: "Da bat dau tai {count} tep.",
    downloadsFailed: "{count} tep khong lay duoc lien ket tai.",
    failedLoadFiles: "Tai danh sach tep that bai",
    failedLoadProjectTasks: "Tai danh sach nhiem vu that bai",
    uploadedFiles: "Da tai len {count} tep.",
    fileUploadFailed: "Tai tep that bai",
    failedDownloadFile: "Tai tep that bai",
    uploadFiles: "Tai tep len",
    targetTask: "Nhiem vu dich",
    projectSharedFolder: "Thu muc dung chung cua du an (khong gan nhiem vu)",
    selectedFiles: "Da chon {count} tep",
    noFilesSelected: "Chua chon tep nao",
    uploading: "Dang tai len...",
    failedLoadProject: "Tai du an that bai",
    taskUpdated: "Da cap nhat nhiem vu.",
    taskCreated: "Da tao nhiem vu.",
    taskSaveFailed: "Luu nhiem vu that bai",
    deleteTaskConfirm: "Xoa nhiem vu nay?",
    taskDeleted: "Da xoa nhiem vu.",
    taskDeletionFailed: "Xoa nhiem vu that bai",
    taskUpdateFailed: "Cap nhat nhiem vu that bai",
    projectUpdated: "Da cap nhat du an.",
    projectUpdateFailed: "Cap nhat du an that bai",
    attachmentUploaded: "Da tai tep dinh kem.",
    uploadFailed: "Tai len that bai",
    attachmentDeleted: "Da xoa tep dinh kem.",
    attachmentDeletionFailed: "Xoa tep dinh kem that bai",
    loadingProject: "Dang tai du an...",
    projectNotFound: "Khong tim thay du an.",
    back: "Quay lai",
    board: "Bang viec",
    gantt: "Gantt",
    table: "Bang",
    projects: "Du an",
    projectName: "Ten du an",
    taskId: "Nhiem vu #",
    priorityHigh: "Cao",
    priorityMedium: "Trung binh",
    priorityLow: "Thap",
    none: "Khong",
    progressPercent: "Tien do (%)",
    remarks: "Ghi chu",
    noAttachments: "Khong co tep dinh kem",
    saving: "Dang luu...",
    subTask: "Nhiem vu con",
    plannedVsActualTimeline: "Tien do ke hoach va thuc te",
    zoomDay: "Ngay",
    zoomWeek: "Tuan",
    zoomMonth: "Thang",
    taskName: "Ten nhiem vu",
    notes: "Ghi chu",
    unassigned: "Chua gan",
    columnTodo: "Can lam",
    columnInProgress: "Dang thuc hien",
    columnDone: "Hoan thanh",
    columnWontDo: "Khong lam",
    columnBacklog: "Danh sach cho",
    accountCreated: "Da tao tai khoan, vui long dang nhap.",
    authenticationFailed: "Xac thuc that bai",
    enterpriseTagline: "Quan ly du an doanh nghiep",
    processing: "Dang xu ly...",
    profileUpdated: "Da cap nhat ho so.",
    profileUpdateFailed: "Cap nhat ho so that bai",
    failedInitializeApp: "Khoi tao ung dung that bai",
    failedLoadProjects: "Tai du an that bai",
    failedRefreshProjects: "Lam moi du an that bai",
    downloadFailed: "Tai xuong that bai",
    previewPlaceholderPdf: "Cho xem truoc PDF (dang phat trien)",
    previewNotAvailable: "Khong ho tro xem truoc voi dinh dang nay."
  }
};

export type ConfigValue = {
  lang: Language;
  setLang: (value: Language) => void;
  theme: Theme;
  setTheme: (value: Theme) => void;
  t: (typeof TRANSLATIONS)["zh"];
};

export const ConfigContext = createContext<ConfigValue>({
  lang: "zh",
  setLang: () => undefined,
  theme: "light",
  setTheme: () => undefined,
  t: TRANSLATIONS.zh
});

export const useConfig = (): ConfigValue => useContext(ConfigContext);
